### ISSUE TITLE
Segmentation fault error on Manjaro. 

### ISSUE THREAD

**Issue by efe3535** [ali019283/dogefetch#12]
![image](https://user-images.githubusercontent.com/46342237/128628609-a2d04350-01e9-4994-bbd4-f3d534d80338.png)

**Comment by efe3535** [comment]
I'll try to run it as superuser.

**Comment by efe3535** [comment]
![image](https://user-images.githubusercontent.com/46342237/128628633-7d9a9ce2-19a2-4670-8cb2-921cf98625b8.png)
Didn't work

**Comment by ali019283** [comment]
Its because the file that contains ascii isnt on /usr/local/share/dogefetch/doggo, either run "sudo make install" or just type "mkdir -p /usr/local/share/dogefetch && sudo cp doggo /usr/local/share/dogefetch/doggo"
