### ISSUE TITLE
Error when running Makefile

### ISSUE THREAD

**Issue by Apolycious** [ali019283/dogefetch#7]
![image](https://user-images.githubusercontent.com/77037457/127252436-efd6212d-5cb5-4086-9939-9eb1b9d748ae.png)
Can anyone help me fix these issues?

**Comment by Athul0515** [comment]
Change 60 to 17 on line 27. That fixed it for me.

**Comment by ali019283** [comment]
Its not really a Error, u can use the program with no worries. Its just a warning,  i will commit and solve this one. (thx to onioneffect)
